<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Oblast extends \Oblast implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdobl()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["idobl"];
        }
        $this->__load();
        return parent::getIdobl();
    }

    public function setNaziv($naziv)
    {
        $this->__load();
        return parent::setNaziv($naziv);
    }

    public function getNaziv()
    {
        $this->__load();
        return parent::getNaziv();
    }

    public function addIdobl2(\Oblast $idobl2)
    {
        $this->__load();
        return parent::addIdobl2($idobl2);
    }

    public function removeIdobl2(\Oblast $idobl2)
    {
        $this->__load();
        return parent::removeIdobl2($idobl2);
    }

    public function getIdobl2()
    {
        $this->__load();
        return parent::getIdobl2();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idobl', 'naziv', 'idobl2');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}