<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Pitanje extends \Pitanje implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdpit()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["idpit"];
        }
        $this->__load();
        return parent::getIdpit();
    }

    public function setBrtacno($brtacno)
    {
        $this->__load();
        return parent::setBrtacno($brtacno);
    }

    public function getBrtacno()
    {
        $this->__load();
        return parent::getBrtacno();
    }

    public function setBrnetacno($brnetacno)
    {
        $this->__load();
        return parent::setBrnetacno($brnetacno);
    }

    public function getBrnetacno()
    {
        $this->__load();
        return parent::getBrnetacno();
    }

    public function setIdniv(\NivoTezine $idniv = NULL)
    {
        $this->__load();
        return parent::setIdniv($idniv);
    }

    public function getIdniv()
    {
        $this->__load();
        return parent::getIdniv();
    }

    public function setIdobl(\Oblast $idobl = NULL)
    {
        $this->__load();
        return parent::setIdobl($idobl);
    }

    public function getIdobl()
    {
        $this->__load();
        return parent::getIdobl();
    }

    public function setIdkor(\Moderator $idkor = NULL)
    {
        $this->__load();
        return parent::setIdkor($idkor);
    }

    public function getIdkor()
    {
        $this->__load();
        return parent::getIdkor();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idpit', 'brtacno', 'brnetacno', 'idniv', 'idobl', 'idkor');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}