<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Takmicar extends \Takmicar implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setIme($ime)
    {
        $this->__load();
        return parent::setIme($ime);
    }

    public function getIme()
    {
        $this->__load();
        return parent::getIme();
    }

    public function setPrezime($prezime)
    {
        $this->__load();
        return parent::setPrezime($prezime);
    }

    public function getPrezime()
    {
        $this->__load();
        return parent::getPrezime();
    }

    public function setSlika($slika)
    {
        $this->__load();
        return parent::setSlika($slika);
    }

    public function getSlika()
    {
        $this->__load();
        return parent::getSlika();
    }

    public function setIdkor(\RegKorisnik $idkor)
    {
        $this->__load();
        return parent::setIdkor($idkor);
    }

    public function getIdkor()
    {
        $this->__load();
        return parent::getIdkor();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'ime', 'prezime', 'slika', 'idkor');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}